#pragma once

#include <cstddef>
#include <cstdint>

namespace maharajah {

// The network compiled into the engine (sources/NnueDefault.cpp, generated by
// tools/embed_net.py): default_network_size bytes of a .nnue file, stored as
// little-endian 64-bit words.
extern const char default_network_name[];
extern const std::size_t default_network_size;
extern const std::uint64_t default_network_words[];

} // namespace maharajah
