#include "../headers/Bitboard.h"
#include "../headers/tables/MagicNumbersTable.h"
#include "gtest/gtest.h"

#include <vector>

using namespace std;
using namespace maharajah;

class magic_numbers_test_fixture : public testing::Test {
  protected:
  void SetUp() override;
};

void magic_numbers_test_fixture::SetUp() {
  init_all();
}

/**
 * @brief Tests whether a given magic number produces a valid magic square attack table for a given piece on a given square.
 *
 * @param square The square on which the piece is located.
 * @param magic The magic number to test.
 * @param relevant_bits The number of relevant bits in the magic number.
 * @param bishop Whether to test the magic number for a bishop or a rook.
 *
 * @return true if the magic number produces a valid magic square attack table, false otherwise.
 */
bool test_magic_square(Squares square, u64 magic, int relevant_bits, bool bishop) {
  const int shift{ 64 - relevant_bits };
  const int occ_count{ 1 << relevant_bits };

  vector<u64> used(occ_count, 0ULL);
  vector<bool> filled(occ_count, false);

  for(int i{}; i < occ_count; i++) {
    u64 occ = set_occupancy(i, relevant_bits, bishop ? bishop_masks[square] : rook_masks[square]);

    u64 attack = bishop ? bishop_attacks_on_the_fly(square, occ) : rook_attacks_on_the_fly(square, occ);

    if(const u64 index = (occ * magic) >> shift; !filled[index]) {
      filled[index] = true;
      used[index] = attack;
    } else if(used[index] != attack) {
      return false; // collision
    }
  }

  return true;
}

/**
 * @brief Tests whether the magic numbers found for each square are non-zero.
 *
 * This test checks whether the magic numbers found for each square are non-zero.
 * If any magic number is zero, the test fails.
 */
TEST_F(magic_numbers_test_fixture, magic_numbers_nonzero) {
  for(const auto square : all_squares) {
    EXPECT_NE(bishop_magic_numbers_table[square], 0ULL);
    EXPECT_NE(rook_magic_numbers_table[square], 0ULL);
  }
}

/**
 * @brief Tests whether the magic numbers found for bishops are collision-free.
 *
 * This test iterates over all squares and checks whether the magic number found for
 * the bishop on that square is collision-free, i.e. there are no collisions between
 * the different occupancies of the board and the attacks generated by the bishop for
 * that occupancy. If a collision is found, the test fails.
 */
TEST_F(magic_numbers_test_fixture, bishop_magics_are_collision_free) {
  for(const auto square : all_squares) {
    ASSERT_TRUE(test_magic_square(square, bishop_magic_numbers_table[square], bishop_relevant_bits[square], true))
        << "Bishop magic collision at square " << square;
  }
}

/**
 * @brief Tests whether the magic numbers found for rooks are collision-free.
 *
 * This test iterates over all squares and checks whether the magic number found for
 * the rook on that square is collision-free, i.e. there are no collisions between
 * the different occupancies of the board and the attacks generated by the rook for
 * that occupancy. If a collision is found, the test fails.
 */
TEST_F(magic_numbers_test_fixture, rook_magics_are_collision_free) {
  for(const auto square : all_squares) {
    ASSERT_TRUE(test_magic_square(square, rook_magic_numbers_table[square], rook_relevant_bits[square], false)) << "Rook magic collision at square " << square;
  }
}
