#!/usr/bin/env python3
"""Writes sources/NnueDefault.cpp, the network compiled into the engine, from a .nnue file.

Usage: python3 tools/embed_net.py nets/net4_768.nnue

The bytes go in as little-endian 64-bit words: an array of 1.7 M byte values takes
compilers far longer, and MSVC caps string literals at 64 KB. Every target (x86-64,
arm64, wasm32) is little-endian, so the words read back as the original bytes.
"""
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = sys.argv[1]
    with open(path, 'rb') as file:
        data = file.read()
    if data[:4] != b'MHNN':
        sys.exit(f'{path}: not a Maharajah network')
    name = os.path.splitext(os.path.basename(path))[0]
    padded = data + bytes(-len(data) % 8)
    words = struct.unpack(f'<{len(padded) // 8}Q', padded)

    lines = [
        f'// Generated by tools/embed_net.py from nets/{os.path.basename(path)}; do not edit.',
        '#include "../headers/NnueDefault.h"',
        '',
        'namespace maharajah {',
        '',
        f'const char default_network_name[]{{ "{name}" }};',
        f'const std::size_t default_network_size{{ {len(data)} }};',
        f'alignas(64) const std::uint64_t default_network_words[]{{',
    ]
    for begin in range(0, len(words), 8):
        lines.append(','.join(f'0x{word:x}' for word in words[begin:begin + 8]) + ',')
    lines += ['};', '', '} // namespace maharajah', '']

    out = os.path.join(ROOT, 'sources', 'NnueDefault.cpp')
    with open(out, 'w', newline='\n') as file:
        file.write('\n'.join(lines))
    print(f'{out}: {name}, {len(data)} bytes')


if __name__ == '__main__':
    main()
